---
swagger: '2.0'
info:
  version: 0.0.1
  title: Appuio Kubernetes API gateway
paths:
  /namespaces:
    get:
      tags:
        - namespace
      produces:
        - application/json
      operationId: getManagedNamespaces
      responses:
        200:
          description: returns a list of namespaces
          schema:
            type: array
            description: list of namespaces
            items:
              $ref: '#/definitions/namespace'
  /namespace/{namespace}/{name}:
    get:
      tags:
        - namespace
      parameters:
      - type: string
        format: string
        name: name
        in: path
        required: true
      - type: string
        format: string
        name: namespace
        in: path
        required: true
      produces:
        - text/json
      operationId: getManagedNamespace
      responses:
        200:
          description: returns a single namespace
          schema:
            type: object
            $ref: '#/definitions/namespace'


definitions:
  namespace:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        minLength: 1
