---
swagger: '2.0'
info:
  version: 0.0.1
  title: Appuio Kubernetes API gateway
paths:
  /namespaces:
    get:
      tags:
        - namespace
      produces:
        - application/json
      operationId: getManagedNamespaces
      responses:
        200:
          description: returns a list of namespaces
          schema:
            type: array
            description: list of namespaces
            items:
              $ref: '#/definitions/namespace'
  /namespace/{customer}/{name}:
    delete:
      tags:
        - namespace
      parameters:
      - type: string
        format: string
        name: name
        in: path
        required: true
      - type: string
        format: string
        name: customer
        in: path
        required: true
      produces:
        - application/json
      operationId: deleteManagedNamespace
      responses:
        200:
          description: deletes a single namespace
          schema:
            type: object
            $ref: '#/definitions/namespace'
    get:
      tags:
        - namespace
      parameters:
      - type: string
        format: string
        name: name
        in: path
        required: true
      - type: string
        format: string
        name: customer
        in: path
        required: true
      produces:
        - application/json
      operationId: getManagedNamespace
      responses:
        200:
          description: returns a single namespace
          schema:
            type: object
            $ref: '#/definitions/namespace'
  /namespace/{customer}:
    put:
      tags:
        - namespace
      parameters:
      - type: string
        format: string
        name: customer
        in: path
        required: true
      - name: body
        in: body
        schema:
          $ref: "#/definitions/namespace"
      produces:
        - application/json
      consumes:
        - application/json
      operationId: createManagedNamespace
      responses:
        200:
          description: create a new managed namespace
          schema:
            type: object
            $ref: '#/definitions/namespace'


definitions:
  namespace:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
