// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// GetManagedNamespacesOKCode is the HTTP code returned for type GetManagedNamespacesOK
const GetManagedNamespacesOKCode int = 200

/*GetManagedNamespacesOK returns a list of namespaces

swagger:response getManagedNamespacesOK
*/
type GetManagedNamespacesOK struct {

	/*list of namespaces
	  In: Body
	*/
	Payload []*models.Namespace `json:"body,omitempty"`
}

// NewGetManagedNamespacesOK creates GetManagedNamespacesOK with default headers values
func NewGetManagedNamespacesOK() *GetManagedNamespacesOK {

	return &GetManagedNamespacesOK{}
}

// WithPayload adds the payload to the get managed namespaces o k response
func (o *GetManagedNamespacesOK) WithPayload(payload []*models.Namespace) *GetManagedNamespacesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get managed namespaces o k response
func (o *GetManagedNamespacesOK) SetPayload(payload []*models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManagedNamespacesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Namespace, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
