// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Appuio Kubernetes API gateway",
    "version": "0.0.1"
  },
  "paths": {
    "/namespace/{customer}": {
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "createManagedNamespace",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "name": "customer",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/namespace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create a new managed namespace",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/namespace"
            }
          }
        }
      }
    },
    "/namespace/{customer}/{name}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "getManagedNamespace",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "string",
            "name": "customer",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns a single namespace",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/namespace"
            }
          }
        }
      }
    },
    "/namespaces": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "getManagedNamespaces",
        "responses": {
          "200": {
            "description": "returns a list of namespaces",
            "schema": {
              "description": "list of namespaces",
              "type": "array",
              "items": {
                "$ref": "#/definitions/namespace"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "namespace": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Appuio Kubernetes API gateway",
    "version": "0.0.1"
  },
  "paths": {
    "/namespace/{customer}": {
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "createManagedNamespace",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "name": "customer",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/namespace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create a new managed namespace",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/namespace"
            }
          }
        }
      }
    },
    "/namespace/{customer}/{name}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "getManagedNamespace",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "string",
            "name": "customer",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns a single namespace",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/namespace"
            }
          }
        }
      }
    },
    "/namespaces": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "namespace"
        ],
        "operationId": "getManagedNamespaces",
        "responses": {
          "200": {
            "description": "returns a list of namespaces",
            "schema": {
              "description": "list of namespaces",
              "type": "array",
              "items": {
                "$ref": "#/definitions/namespace"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "namespace": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "description": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
