// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// GetAllClustersOKCode is the HTTP code returned for type GetAllClustersOK
const GetAllClustersOKCode int = 200

/*GetAllClustersOK returns all clusters

swagger:response getAllClustersOK
*/
type GetAllClustersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Cluster `json:"body,omitempty"`
}

// NewGetAllClustersOK creates GetAllClustersOK with default headers values
func NewGetAllClustersOK() *GetAllClustersOK {

	return &GetAllClustersOK{}
}

// WithPayload adds the payload to the get all clusters o k response
func (o *GetAllClustersOK) WithPayload(payload []*models.Cluster) *GetAllClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all clusters o k response
func (o *GetAllClustersOK) SetPayload(payload []*models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Cluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
