// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllClustersHandlerFunc turns a function with the right signature into a get all clusters handler
type GetAllClustersHandlerFunc func(GetAllClustersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllClustersHandlerFunc) Handle(params GetAllClustersParams) middleware.Responder {
	return fn(params)
}

// GetAllClustersHandler interface for that can handle valid get all clusters params
type GetAllClustersHandler interface {
	Handle(GetAllClustersParams) middleware.Responder
}

// NewGetAllClusters creates a new http.Handler for the get all clusters operation
func NewGetAllClusters(ctx *middleware.Context, handler GetAllClustersHandler) *GetAllClusters {
	return &GetAllClusters{Context: ctx, Handler: handler}
}

/*GetAllClusters swagger:route GET /clusters cluster getAllClusters

GetAllClusters get all clusters API

*/
type GetAllClusters struct {
	Context *middleware.Context
	Handler GetAllClustersHandler
}

func (o *GetAllClusters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllClustersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
