// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// RegisterClusterOKCode is the HTTP code returned for type RegisterClusterOK
const RegisterClusterOKCode int = 200

/*RegisterClusterOK registers a new cluster

swagger:response registerClusterOK
*/
type RegisterClusterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewRegisterClusterOK creates RegisterClusterOK with default headers values
func NewRegisterClusterOK() *RegisterClusterOK {

	return &RegisterClusterOK{}
}

// WithPayload adds the payload to the register cluster o k response
func (o *RegisterClusterOK) WithPayload(payload *models.Cluster) *RegisterClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register cluster o k response
func (o *RegisterClusterOK) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
