// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// CreateManagedNamespaceOKCode is the HTTP code returned for type CreateManagedNamespaceOK
const CreateManagedNamespaceOKCode int = 200

/*CreateManagedNamespaceOK create a new managed namespace

swagger:response createManagedNamespaceOK
*/
type CreateManagedNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Namespace `json:"body,omitempty"`
}

// NewCreateManagedNamespaceOK creates CreateManagedNamespaceOK with default headers values
func NewCreateManagedNamespaceOK() *CreateManagedNamespaceOK {

	return &CreateManagedNamespaceOK{}
}

// WithPayload adds the payload to the create managed namespace o k response
func (o *CreateManagedNamespaceOK) WithPayload(payload *models.Namespace) *CreateManagedNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create managed namespace o k response
func (o *CreateManagedNamespaceOK) SetPayload(payload *models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateManagedNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
