// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// DeleteManagedNamespaceOKCode is the HTTP code returned for type DeleteManagedNamespaceOK
const DeleteManagedNamespaceOKCode int = 200

/*DeleteManagedNamespaceOK deletes a single namespace

swagger:response deleteManagedNamespaceOK
*/
type DeleteManagedNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Namespace `json:"body,omitempty"`
}

// NewDeleteManagedNamespaceOK creates DeleteManagedNamespaceOK with default headers values
func NewDeleteManagedNamespaceOK() *DeleteManagedNamespaceOK {

	return &DeleteManagedNamespaceOK{}
}

// WithPayload adds the payload to the delete managed namespace o k response
func (o *DeleteManagedNamespaceOK) WithPayload(payload *models.Namespace) *DeleteManagedNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete managed namespace o k response
func (o *DeleteManagedNamespaceOK) SetPayload(payload *models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteManagedNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
