// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetManagedNamespacesHandlerFunc turns a function with the right signature into a get managed namespaces handler
type GetManagedNamespacesHandlerFunc func(GetManagedNamespacesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetManagedNamespacesHandlerFunc) Handle(params GetManagedNamespacesParams) middleware.Responder {
	return fn(params)
}

// GetManagedNamespacesHandler interface for that can handle valid get managed namespaces params
type GetManagedNamespacesHandler interface {
	Handle(GetManagedNamespacesParams) middleware.Responder
}

// NewGetManagedNamespaces creates a new http.Handler for the get managed namespaces operation
func NewGetManagedNamespaces(ctx *middleware.Context, handler GetManagedNamespacesHandler) *GetManagedNamespaces {
	return &GetManagedNamespaces{Context: ctx, Handler: handler}
}

/*GetManagedNamespaces swagger:route GET /{clustername}/namespaces namespace getManagedNamespaces

GetManagedNamespaces get managed namespaces API

*/
type GetManagedNamespaces struct {
	Context *middleware.Context
	Handler GetManagedNamespacesHandler
}

func (o *GetManagedNamespaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetManagedNamespacesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
