// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// GetManagedNamespaceOKCode is the HTTP code returned for type GetManagedNamespaceOK
const GetManagedNamespaceOKCode int = 200

/*GetManagedNamespaceOK returns a single namespace

swagger:response getManagedNamespaceOK
*/
type GetManagedNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Namespace `json:"body,omitempty"`
}

// NewGetManagedNamespaceOK creates GetManagedNamespaceOK with default headers values
func NewGetManagedNamespaceOK() *GetManagedNamespaceOK {

	return &GetManagedNamespaceOK{}
}

// WithPayload adds the payload to the get managed namespace o k response
func (o *GetManagedNamespaceOK) WithPayload(payload *models.Namespace) *GetManagedNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get managed namespace o k response
func (o *GetManagedNamespaceOK) SetPayload(payload *models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetManagedNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
