// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vshn/cdays-webapi-poc/models"
)

// UpdateManagedNamespaceOKCode is the HTTP code returned for type UpdateManagedNamespaceOK
const UpdateManagedNamespaceOKCode int = 200

/*UpdateManagedNamespaceOK deletes a single namespace

swagger:response updateManagedNamespaceOK
*/
type UpdateManagedNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Namespace `json:"body,omitempty"`
}

// NewUpdateManagedNamespaceOK creates UpdateManagedNamespaceOK with default headers values
func NewUpdateManagedNamespaceOK() *UpdateManagedNamespaceOK {

	return &UpdateManagedNamespaceOK{}
}

// WithPayload adds the payload to the update managed namespace o k response
func (o *UpdateManagedNamespaceOK) WithPayload(payload *models.Namespace) *UpdateManagedNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update managed namespace o k response
func (o *UpdateManagedNamespaceOK) SetPayload(payload *models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateManagedNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
